const dataPelis =
  [
    {
      "id": 1156594,
      "titulo": "Culpa nuestra",
      "fecha": "2025-10-15",
      "duracion": 113,
      "clasificacion": "APT",
      "genero": "Romance, Drama",
      "sinopsis": "La boda de Jenna y Lion propicia el tan deseado reencuentro entre Noah y Nick tiempo después de su ruptura. La incapacidad de Nick para perdonar a Noah se alza como una barrera insalvable. Él, heredero de las empresas de su abuelo y ella, empezando su vida laboral, se resisten a alimentar una llama que aún sigue viva. Pero una vez que sus caminos se han vuelto a cruzar, ¿será el amor más fuerte que el rencor? Secuela de \"Culpa tuya\".",
      "idioma": "ES",
      "poster": "https://image.tmdb.org/t/p/w500/6kmi6vmp6iOn4KzI7WfnVtAeJhU.jpg",
      "background": "https://image.tmdb.org/t/p/w500/7QirCB1o80NEFpQGlQRZerZbQEp.jpg",
      "trailer": "https://www.youtube.com/embed/g4rcFcbYGv8",
      "formato": "Regular",
    },
    {
      "id": 1311031,
      "titulo": "Kimetsu no Yaiba La fortaleza infinita",
      "fecha": "2025-07-18",
      "duracion": 155,
      "clasificacion": "APT",
      "genero": "Animación, Acción, Fantasía, Suspense",
      "sinopsis": "El Cuerpo de Cazadores de Demonios se enfrenta a los Doce Kizuki restantes antes de enfrentarse a Muzan en el Castillo del Infinito para derrotarlo de una vez por todas.",
      "idioma": "JA",
      "poster": "https://image.tmdb.org/t/p/w500/jl7e0hLYwIDsMlEQ28Gh30DoJRy.jpg",
      "background": "https://image.tmdb.org/t/p/w500/1RgPyOhN4DRs225BGTlHJqCudII.jpg",
      "trailer": "https://www.youtube.com/embed/X3E4zogzWsY",
      "formato": "Prime",
    },
    {
      "id": 1197137,
      "titulo": "Black Phone 2",
      "fecha": "2025-10-15",
      "duracion": 114,
      "clasificacion": "APT",
      "genero": "Terror, Suspense",
      "sinopsis": "La película Black Phone 2 (2025) es una secuela ambientada en 1982, cuatro años después de que Finney Blake lograra matar al secuestrador y asesino en serie conocido como \"The Grabber\". Finney, ahora marcado por el trauma, junto a su hermana menor Gwen, que tiene habilidades psíquicas, comienzan a tener visiones relacionadas con asesinatos ocurridos en un campamento cristiano en las Montañas Rocosas. Decididos a descubrir la verdad, viajan junto con Ernesto, un amigo, al campamento donde trabajó su madre, que también tenía dones psíquicos y fue víctima del asesino.",
      "idioma": "EN",
      "poster": "https://image.tmdb.org/t/p/w500/q2G2EsnMaDzcWJetfpxnqMu4smE.jpg",
      "background": "https://image.tmdb.org/t/p/w500/GNeuKnbZRZj5JhKfnJOPyKJuVA.jpg",
      "trailer": "https://www.youtube.com/embed/vbjRY7KeZe0",
      "formato": "Prime",
    },
    {
      "id": 1010756,
      "titulo": "Strangers: Capítulo 2",
      "fecha": "2025-09-25",
      "duracion": 98,
      "clasificacion": "APT",
      "genero": "Terror, Suspense",
      "sinopsis": "De camino a su luna de miel, el vehículo de una pareja se avería, obligándoles a refugiarse en un remoto Airbnb. Al caer la noche, tres desconocidos enmascarados los aterrorizan hasta el amanecer.",
      "idioma": "EN",
      "poster": "https://image.tmdb.org/t/p/w500/fSRRH7UasrE6q240H00dww3vE1c.jpg",
      "background": "https://image.tmdb.org/t/p/w500/sSaUmM4bnZJ7PW5dlyRi7iONB65.jpg",
      "trailer": "https://www.youtube.com/embed/vxp64gTBSxI",
      "formato": "Regular",
    },
    {
      "id": 617126,
      "titulo": "Los Cuatro Fantásticos: Primeros pasos",
      "fecha": "2025-07-23",
      "duracion": 115,
      "clasificacion": "APT",
      "genero": "Ciencia ficción, Aventura",
      "sinopsis": "Con un mundo retrofuturista inspirado en los años 60 como telón de fondo, la Primera Familia de Marvel deberá hacer frente a su mayor desafío hasta la fecha. Obligados a buscar el equilibrio entre su papel de héroes y sus fuertes vínculos familiares, tendrán que defender la Tierra de un hambriento dios espacial llamado Galactus y su intrigante heraldo, Estela Plateada.",
      "idioma": "EN",
      "poster": "https://image.tmdb.org/t/p/w500/ckfiXWGEMWrUP53cc6QyHijLlhl.jpg",
      "background": "https://image.tmdb.org/t/p/w500/hBvaanw3RfMEs1m1blY7xwRXzul.jpg",
      "trailer": "https://www.youtube.com/embed/L1lCRrgTOc4",
      "formato": "Prime",
    },
    {

      "id": 941109,
      "titulo": "Juego sucio",
      "fecha": "2025-09-30",
      "duracion": 125,
      "clasificacion": "+18",
      "genero": "Crimen",
      "sinopsis": "Un experto ladrón lleva a cabo el mayor robo de su vida. Parker, junto a Grofield, Zen y un equipo experto, se ven involucrados en un golpe que los enfrenta a la mafia de Nueva York en esta arriesgada misión.",
      "idioma": "EN",
      "poster": "https://image.tmdb.org/t/p/w500/70Na5MXfOsFlJvoX6oKYAwOhNN9.jpg",
      "background": "https://image.tmdb.org/t/p/w500/k6tdiMTO39RQj3dhfspuzprfoe0.jpg",
      "trailer": "https://www.youtube.com/embed/ey_qiYSaPko",
      "formato": "Regular",
    },
    {
      "id": 575265,
      "titulo": "Misión: Imposible - Sentencia final",
      "fecha": "2025-05-17",
      "duracion": 169,
      "clasificacion": "APT",
      "genero": "Acción, Aventura, Suspense",
      "sinopsis": "El agente Ethan Hunt continúa su misión de impedir que Gabriel controle el tecnológicamente omnipotente programa de IA conocido como \"the Entity\".",
      "idioma": "EN",
      "poster": "https://image.tmdb.org/t/p/w500/haOjJGUV00dKlZaJWgjM1UD1cJV.jpg",
      "background": "https://image.tmdb.org/t/p/w500/538U9snNc2fpnOmYXAPUh3zn31H.jpg",
      "trailer": "https://www.youtube.com/embed/YqtdLeJSM6o",
      "formato": "Prime",
    },
    {
      "id": 1257009,
      "titulo": "Primitive War",
      "fecha": "2025-08-21",
      "duracion": 133,
      "clasificacion": "APT",
      "genero": "Acción, Terror, Bélica",
      "sinopsis": "Vietnam, 1968. El equipo de reconocimiento Vulture Squad se adentra en un valle aislado para investigar un pelotón de Boinas Verdes desaparecido. Su misión toma un giro oscuro cuando descubren una amenaza invisible.",
      "idioma": "EN",
      "poster": "https://image.tmdb.org/t/p/w500/aJc0Ej0mAIpNPoQh46oOnUQCqxE.jpg",
      "background": "https://image.tmdb.org/t/p/w500/bWF5ImUscXXYia8owpm8coadR4m.jpg",
      "trailer": "https://www.youtube.com/embed/9F_WwYA7DR0",
      "formato": "Prime",
    },
    {
      "id": 1061474,
      "titulo": "Superman",
      "fecha": "2025-07-09",
      "duracion": 129,
      "clasificacion": "APT",
      "genero": "Ciencia ficción, Aventura, Acción",
      "sinopsis": "En un mundo que ha perdido la fe en la bondad, Superman lucha por reconciliar su herencia kryptoniana con los valores humanos que moldearon su carácter. Criado en la Tierra, representa la verdad, la justicia y el estilo americano, pero debe enfrentarse a un mundo cínico que cuestiona sus ideales. Entre el deber de proteger a la humanidad y la búsqueda de su identidad, Superman demuestra que la esperanza y la bondad nunca pasan de moda, incluso en los tiempos más oscuros, inspirando a otros a creer en un futuro mejor.",
      "idioma": "EN",
      "poster": "https://image.tmdb.org/t/p/w500/fvUJb08yatV2b3NUSwuYdQKYoFd.jpg",
      "background": "https://image.tmdb.org/t/p/w500/eGX66zonvc4bXg3rM08RUxdYSDx.jpg",
      "trailer": "https://www.youtube.com/embed/KWoJAz9YiPc",
      "formato": "Regular",
    },
    {
      "id": 1290879,
      "titulo": "La mujer del camarote 10",
      "fecha": "2025-10-09",
      "duracion": 95,
      "clasificacion": "APT",
      "genero": "Misterio, Suspense, Crimen",
      "sinopsis": "A bordo de un lujoso yate por motivos de trabajo, una periodista ve como alguien cae al mar. Pero cuando nadie la cree, decide arriesgar su propia vida para descubrir la verdad.",
      "idioma": "EN",
      "poster": "https://image.tmdb.org/t/p/w500/lUJIBUjEab71fJ8U9gs0NouUJ18.jpg",
      "background": "https://image.tmdb.org/t/p/w500/9IHZeCusOd7RUaQpUrQJlKqjsUZ.jpg",
      "trailer": "https://www.youtube.com/embed/rL8Vn4Is_sk",
      "formato": "Regular",
    },
    {
      "id": 533533,
      "titulo": "TRON: Ares",
      "fecha": "2025-10-08",
      "duracion": 119,
      "clasificacion": "APT",
      "genero": "Ciencia ficción, Aventura, Acción",
      "sinopsis": "La historia de Ares, un programa muy sofisticado que se envía desde el mundo digital al mundo real en una misión peligrosa y que va a representar el primer encuentro de la humanidad con seres creados por la IA.",
      "idioma": "EN",
      "poster": "https://image.tmdb.org/t/p/w500/qShQABLVRMZKnv5mWOPXWniBeB3.jpg",
      "background": "https://image.tmdb.org/t/p/w500/np0dsehLDdbfyHFRtqCiL1GR0TQ.jpg",
      "trailer": "https://www.youtube.com/embed/Q1bvwjV5u3Q",
      "formato": "Prime",
    },
    {
      "id": 1267905,
      "titulo": "Los Rose",
      "fecha": "2025-08-27",
      "duracion": 105,
      "clasificacion": "APT",
      "genero": "Comedia, Drama, Romance",
      "sinopsis": "La vida parece fácil para la pareja perfecta que forman Ivy y Theo: carreras de éxito, un matrimonio feliz y unos hijos estupendos. Pero detrás de la fachada de su supuesta vida ideal, se avecina una tormenta: la carrera de Theo se desploma mientras que las ambiciones de Ivy despegan, lo que desencadena una caja de Pandora de competitividad y resentimiento ocultos.",
      "idioma": "EN",
      "poster": "https://image.tmdb.org/t/p/w500/lXumhtgMOxA3aqocplC8YIMwOv8.jpg",
      "background": "https://image.tmdb.org/t/p/w500/h4HSZjOeAoHQ3qPuy6x9Cyr69bS.jpg",
      "trailer": "https://www.youtube.com/embed/0RuTQmZFzTU",
      "formato": "Prime",
    },
    {
      "id": 1234821,
      "titulo": "Jurassic World: El renacer",
      "fecha": "2025-07-01",
      "duracion": 133,
      "clasificacion": "APT",
      "genero": "Ciencia ficción, Aventura, Acción",
      "sinopsis": "Cinco años después de los eventos de \"Dominion\", la ecología del planeta ha demostrado ser insoportable para los dinosaurios, donde los pocos que quedan viven aislados en las regiones ecuatoriales. Zora Bennett es contratada para dirigir a un equipo de especialistas cuyo objetivo es conseguir el material genético de las tres criaturas más grandes, las cuales tienen en su ADN la clave para fabricar un medicamento que aportará grandes beneficios a la humanidad. Pero la operación se cruzará con una familia cuyo barco volcó y todos acabarán en una isla prohibida ocupada por dinosaurios de numerosas especies, donde tendrán que hacer lo imposible para sobrevivir.",
      "idioma": "EN",
      "poster": "https://image.tmdb.org/t/p/w500/2sbGd7kDhMicDkT097FR9a2JyGU.jpg",
      "background": "https://image.tmdb.org/t/p/w500/8fA0Gr4vJNPOd0jyqWKU7ef8DoH.jpg",
      "trailer": "https://www.youtube.com/embed/1R3LTANp7hw",
      "formato": "Regular",
    },
    {
      "id": 1078605,
      "titulo": "Weapons",
      "fecha": "2026-02-04",
      "duracion": 129,
      "clasificacion": "APT",
      "genero": "Terror, Misterio",
      "sinopsis": "Cuando todos los alumnos de una misma clase, salvo uno, desaparecen misteriosamente la misma noche y exactamente a la misma hora, la pequeña ciudad donde viven se pregunta quién o qué está detrás de su desaparición.",
      "idioma": "EN",
      "poster": "https://image.tmdb.org/t/p/w500/nYqEQ3ltw0hHc1kBaNWr7Rb8WNZ.jpg",
      "background": "https://image.tmdb.org/t/p/w500/Q2OajDi2kcO6yErb1IAyVDTKMs.jpg",
      "trailer": "https://www.youtube.com/embed/lZyASo3yaTA",
      "formato": "Regular",
    },
    {
      "id": 1054867,
      "titulo": "Una batalla tras otra",
      "fecha": "2026-02-23",
      "duracion": 162,
      "clasificacion": "APT",
      "genero": "Acción, Suspense, Crimen",
      "sinopsis": "Cuando su principal enemigo resurge después de 16 años, una banda de ex revolucionarios se pone de nuevo en contacto para rescatar a la hija de uno de los suyos, encarnado por Leonardo DiCaprio. Adaptación de la novela 'Vineland', de Thomas Pynchon (1990), sobre los movimientos radicales de los años sesenta.",
      "idioma": "EN",
      "poster": "https://image.tmdb.org/t/p/w500/zwxROLIUeEr6eFITwworjcXLAk4.jpg",
      "background": "https://image.tmdb.org/t/p/w500/nIX9kqNNe4ERx3wg3TuzRa2deAM.jpg",
      "trailer": "https://www.youtube.com/embed/U_wQ_20g8Jw",
      "formato": "Regular",
    },
    {
      "id": 1294203,
      "titulo": "Culpa mía: Londres",
      "fecha": "2025-02-12",
      "duracion": 119,
      "clasificacion": "+14",
      "genero": "Romance, Drama",
      "sinopsis": "Noah, de 18 años, se traslada de Estados Unidos a Londres con su madre, que se ha enamorado recientemente de William, un adinerado hombre de negocios británico. Noah conoce al hijo de William, el malote Nick. Pese a los esfuerzos de ambos por evitarlo, se sienten atraídos. Mientras Noah pasa el verano adaptándose a su nueva vida, su doloroso pasado la irá atrapando a la vez que se va enamorando.",
      "idioma": "EN",
      "poster": "https://image.tmdb.org/t/p/w500/q0HxfkF9eoa6wSVnzwMhuDSK7ba.jpg",
      "background": "https://image.tmdb.org/t/p/w500/uJK0jjJ8QDOQw5lcNBwu059ht4D.jpg",
      "trailer": "https://www.youtube.com/embed/RdoTDJ96Dwc",
      "formato": "Prime",
    },
    {
      "id": 1087192,
      "titulo": "Cómo entrenar a tu dragón",
      "fecha": "2025-06-06",
      "duracion": 125,
      "clasificacion": "APT",
      "genero": "Fantasía, Familia, Acción, Aventura",
      "sinopsis": "En la escarpada isla de Mema, donde vikingos y dragones han sido enemigos acérrimos durante generaciones, Hipo se desmarca desafiando siglos de tradición cuando entabla amistad con Desdentao, un temido dragón Furia Nocturna. Su insólito vínculo revela la verdadera naturaleza de los dragones y desafía los cimientos de la sociedad vikinga.",
      "idioma": "EN",
      "poster": "https://image.tmdb.org/t/p/w500/kjQXYc2Abhy3TBgAZGzJRhN1JaV.jpg",
      "background": "https://image.tmdb.org/t/p/w500/AeDzjt00Hfh9CuW7TIUdYBJmWYM.jpg",
      "trailer": "https://www.youtube.com/embed/Ns6ZEpQ1xS0",
      "formato": "Regular",
    },
        {
      "id": 1038392,
      "titulo": "Expediente Warren: El último rito",
      "fecha": "2026-01-03",
      "duracion": 135,
      "clasificacion": "APT",
      "genero": "Terror",
      "sinopsis": "Los investigadores de lo paranormal Ed y Lorraine Warren se enfrentan a un último caso aterrador en el que están implicadas entidades misteriosas a las que deben enfrentarse.",
      "idioma": "EN",
      "poster": "https://image.tmdb.org/t/p/w500/qdoqogLNR6myoRrxYFxF4UTkFne.jpg",
      "background": "https://image.tmdb.org/t/p/w500/Fb8gyhkAQorxr98jllYoXurWvj.jpg",
      "trailer": "https://www.youtube.com/embed/FIiiMiC7GGY",
      "formato": "Regular",
    },
    {
      "id": 911430,
      "titulo": "F1 la película",
      "fecha": "2025-06-25",
      "duracion": 155,
      "clasificacion": "APT",
      "genero": "Acción, Drama",
      "sinopsis": "El mítico piloto Sonny Hayes vuelve de su retiro, persuadido para liderar un equipo de Fórmula 1 en apuros y guiar a su joven promesa, en busca de una nueva oportunidad de éxito.",
      "idioma": "EN",
      "poster": "https://image.tmdb.org/t/p/w500/wfpqaxoPKvcqzLy8FO0enGXBzU.jpg",
      "background": "https://image.tmdb.org/t/p/w500/ZtcGMc204JsNqfjS9lU6udRgpo.jpg",
      "trailer": "https://www.youtube.com/embed/mizQBIpMrbE",
      "formato": "Regular",
    },
    {
      "id": 1280282,
      "titulo": "La casa de muñecas de Gabby: La película",
      "fecha": "2026-01-13",
      "duracion": 98,
      "clasificacion": "APT",
      "genero": "Familia, Comedia, Aventura, Animación",
      "sinopsis": "El viaje por carretera de Gabby y la abuela Gigi da un giro inesperado cuando la preciada casa de muñecas de Gabby acaba en manos de la excéntrica gatera Vera. Gabby se embarca en una aventura para reunir a los Gabby Cats y recuperar su querida casa de muñecas antes de que sea demasiado tarde.",
      "idioma": "EN",
      "poster": "https://image.tmdb.org/t/p/w500/ruAIbycacQIIXeTf4xh1r1NjvJa.jpg",
      "background": "https://image.tmdb.org/t/p/w500/MrcSSzWGsXf2IUJpjPPFLlNbjX.jpg",
      "trailer": "https://www.youtube.com/embed/speJOtNWaXw",
      "formato": "Prime",
    },
    {
      "id": 1275151,
      "titulo": "Un fantasma en la batalla",
      "fecha": "2026-01-03",
      "duracion": 108,
      "clasificacion": "APT",
      "genero": "Drama, Suspense",
      "sinopsis": "Una joven guardia civil lo deja todo para hacerse pasar por miembro de ETA, arriesgando su vida para localizar los zulos de los terroristas en el sur de Francia.",
      "idioma": "ES",
      "poster": "https://image.tmdb.org/t/p/w500/zMdJdI74PdObENl4RfU3o5lC0VM.jpg",
      "background": "https://image.tmdb.org/t/p/w500/l2Fk70FTuBPDx32gTsVUrRvF8jC.jpg",
      "trailer": "https://www.youtube.com/embed/mLVTmqJxpTY",
      "formato": "Regular",
    },
    {
      "id": 1218925,
      "titulo": "Chainsaw Man - La película: El arco de Reze",
      "fecha": "2025-12-19",
      "duracion": 100,
      "clasificacion": "APT",
      "genero": "Animación, Acción, Fantasía",
      "sinopsis": "Denji trabajaba como cazador de demonios para la yakuza, tratando de saldar la deuda que había heredado de sus padres, pero la yakuza lo traicionó y lo mató. Antes de perder el conocimiento, Pochita, el perro-demonio motosierra de Denji, hizo un trato con él y le salvó la vida. Así se fusionaron, creando al imparable Chainsaw Man. Ahora, en medio de una brutal guerra entre demonios, cazadores y enemigos secretos, una misteriosa chica llamada Reze irrumpe en su mundo y Denji se enfrenta a su batalla más mortífera, impulsado por el amor, en un mundo donde la supervivencia no conoce reglas.",
      "idioma": "JA",
      "poster": "https://image.tmdb.org/t/p/w500/1CfZCb56vWjq37uXtbKNMevMzwG.jpg",
      "background": "https://image.tmdb.org/t/p/w500/kfXgo2rMF1A19celCwLyQ4Xwpf8.jpg",
      "trailer": "https://www.youtube.com/embed/-KpVet_60Yc",
      "formato": "Regular",
    },
    {
      "id": 1175942,
      "titulo": "Los tipos malos 2",
      "fecha": "2026-01-24",
      "duracion": 103,
      "clasificacion": "APT",
      "genero": "Familia, Comedia, Crimen, Aventura, Animación",
      "sinopsis": "Un genial equipo de animales que no respetan la ley, los ahora muy reformados Tipos Malos, se esfuerzan (mucho, muchísimo) en ser buenos, pero se ven envueltos involuntariamente en un golpe de envergadura mundial planeado por un inesperado grupo de criminales: las Tipas Malas.",
      "idioma": "EN",
      "poster": "https://image.tmdb.org/t/p/w500/mZmnKDhIS2yNmtfzde5vtdCYzBF.jpg",
      "background": "https://image.tmdb.org/t/p/w500/lB96EMr5A7Og81UhyldJvvy35r.jpg",
      "trailer": "https://www.youtube.com/embed/PnUcgVUuYjs",
      "formato": "Prime",
    },
    {
      "id": 552524,
      "titulo": "Lilo y Stitch",
      "fecha": "2025-05-17",
      "duracion": 108,
      "clasificacion": "APT",
      "genero": "Familia, Ciencia ficción, Comedia, Aventura",
      "sinopsis": "La conmovedora y divertidísima historia de una solitaria niña hawaiana y el extraterrestre fugitivo que la ayuda a reparar su desestructurada familia.",
      "idioma": "EN",
      "poster": "https://image.tmdb.org/t/p/w500/4oLLOAT55JhAoe73VliaSKFvEEr.jpg",
      "background": "https://image.tmdb.org/t/p/w500/7Zx3wDG5bBtcfk8lcnCWDOLM4Y4.jpg",
      "trailer": "https://www.youtube.com/embed/sa_6BS_VY-M",
      "formato": "Regular",
    },
    {
      "id": 1241921,
      "titulo": "Un gran viaje atrevido y maravilloso",
      "fecha": "2025-12-17",
      "duracion": 109,
      "clasificacion": "APT",
      "genero": "Romance, Fantasía, Drama",
      "sinopsis": "Sarah y David son dos solteros que se conocen en la boda de un amigo común y, pronto, por un sorprendente giro del destino, se embarcan en Un gran viaje atrevido y maravilloso, una aventura divertida, fantástica y arrolladora en la que reviven juntos momentos importantes de sus respectivos pasados, descubriendo cómo han llegado a donde están.",
      "idioma": "EN",
      "poster": "https://image.tmdb.org/t/p/w500/7Ja9exbCZBl3TEHRTWPESHoiln0.jpg",
      "background": "https://image.tmdb.org/t/p/w500/2ha0wAOqrUcLScStWQcgeOOXapQ.jpg",
      "trailer": "https://www.youtube.com/embed/QuOH2kRMU1Q",
      "formato": "Regular",
    },
    {
      "id": 541671,
      "titulo": "Ballerina",
      "fecha": "2025-06-04",
      "duracion": 125,
      "clasificacion": "APT",
      "genero": "Acción, Suspense, Crimen",
      "sinopsis": "Eve Macarro es una asesina entrenada por la Ruska Roma desde su infancia, la misma organización criminal encargada del adiestramiento de John Wick. En esta violenta historia de venganza, Eve intentará por todos los medios averiguar quién está detrás del asesinato de su padre. En su lucha por conocer la verdad, tendrá que atenerse a las normas de la Alta Mesa y, por supuesto, a las del Hotel Continental, donde descubrirá que existen secretos ocultos sobre su pasado.",
      "idioma": "EN",
      "poster": "https://image.tmdb.org/t/p/w500/gQCrYmvCK7JCLXjCGTMRF5Lzr5c.jpg",
      "background": "https://image.tmdb.org/t/p/w500/1yktYsxkmUtUFTUnCAUaqG6FEiz.jpg",
      "trailer": "https://www.youtube.com/embed/7o8yNS4CYws",
      "formato": "Prime",
    },
    {
      "id": 574475,
      "titulo": "Destino final: Lazos de sangre",
      "fecha": "2025-05-14",
      "duracion": 110,
      "clasificacion": "APT",
      "genero": "Terror, Misterio",
      "sinopsis": "Acosada por una violenta pesadilla recurrente, la estudiante universitaria Stefanie se dirige a casa para localizar a la única persona que podría ser capaz de romper el ciclo y salvar a su familia de la espeluznante muerte que inevitablemente les espera a todos.",
      "idioma": "EN",
      "poster": "https://image.tmdb.org/t/p/w500/frNkbclQpexf3aUzZrnixF3t5Hw.jpg",
      "background": "https://image.tmdb.org/t/p/w500/uIpJPDNFoeX0TVml9smPrs9KUVx.jpg",
      "trailer": "https://www.youtube.com/embed/jO0pT3Q4Rms",
      "formato": "Regular",
    },
    {
      "id": 1022787,
      "titulo": "Elio",
      "fecha": "2025-12-18",
      "duracion": 98,
      "clasificacion": "APT",
      "genero": "Familia, Comedia, Aventura, Animación, Ciencia ficción",
      "sinopsis": "Cuenta la historia de Elio, un niño de 11 años, que lucha por encajar hasta que de repente es transportado por extraterrestres y es elegido para ser el embajador galáctico de la Tierra.",
      "idioma": "EN",
      "poster": "https://image.tmdb.org/t/p/w500/fqF7z5A8kFIrNtSdpEfjE539fna.jpg",
      "background": "https://image.tmdb.org/t/p/w500/7yzpHj2ssuwJERjj4y2MDoZDtRN.jpg",
      "trailer": "https://www.youtube.com/embed/U0VCAsn51ZU",
      "formato": "Regular",
    },
    {
      "id": 1035259,
      "titulo": "Agárralo como puedas",
      "fecha": "2025-07-30",
      "duracion": 85,
      "clasificacion": "APT",
      "genero": "Comedia, Acción, Crimen",
      "sinopsis": "El torpe teniente Frank Drebin Jr. intenta resolver un asesinato vinculado a un magnate tecnológico. Mientras investiga, su unidad policial corre peligro de ser cerrada. Con la ayuda de una escritora de crímenes, Frank se verá envuelto en situaciones tan absurdas como explosivas. Película reboot basada en la popular franquicia de comedia \"Agárralo como puedas\" y la serie de televisión \"Police Squad!\".",
      "idioma": "EN",
      "poster": "https://image.tmdb.org/t/p/w500/Mu73AnUmBpSI8W0bNCgaCVwzOa.jpg",
      "background": "https://image.tmdb.org/t/p/w500/kzeBfhXMRWiykBsqoL3UbfaM0S.jpg",
      "trailer": "https://www.youtube.com/embed/AyF3ttDC8H0",
      "formato": "Regular",
    },
    {
      "id": 986097,
      "titulo": "El mejor",
      "fecha": "2025-09-18",
      "duracion": 96,
      "clasificacion": "APT",
      "genero": "Terror, Misterio",
      "sinopsis": "Cameron Cade es un quarterback en ciernes que ha dedicado su vida y su identidad al fútbol americano. En vísperas del campeonato anual de fútbol americano profesional, Cam es atacado por un hincha desquiciado y sufre un traumatismo cerebral que podría poner fin a su carrera. Justo cuando todo parece perdido, Cam recibe un salvavidas cuando su héroe, Isaiah White, un legendario quarterback ocho veces campeón y megaestrella cultural, se ofrece a entrenar a Cam en el aislado complejo que Isaiah comparte con su esposa, Elsie White. Pero a medida que el entrenamiento de Cam se acelera, el carisma de Isaiah comienza a cuajar en algo más oscuro, enviando a su protegido a un agujero de conejo desorientador que puede costarle más de lo que jamás esperó.",
      "idioma": "EN",
      "poster": "https://image.tmdb.org/t/p/w500/n2xPRI0isWxKfX3UqlfnNPaPusg.jpg",
      "background": "https://image.tmdb.org/t/p/w500/jzzpCJWkVZZwAxzzLmtYN0MBWFd.jpg",
      "trailer": "https://www.youtube.com/embed/Dz7z_I4ceTY",
      "formato": "Regular",
    },
    {
      "id": 1236470,
      "titulo": "Laberinto en llamas",
      "fecha": "2025-09-19",
      "duracion": 130,
      "clasificacion": "APT",
      "genero": "Drama, Misterio, Suspense",
      "sinopsis": "En uno de los incendios forestales más mortíferos de la historia de Estados Unidos que amenaza la ciudad de Paradise, Kevin McKay, un conductor de autobús escolar, y Mary Ludwig, una maestra infantil, luchan para salvar a 22 niños del aterrador infierno.",
      "idioma": "EN",
      "poster": "https://image.tmdb.org/t/p/w500/8n0kkUc4wKknqEJfq8eErWrvvUL.jpg",
      "background": "https://image.tmdb.org/t/p/w500/lL4zajQbvvo63z2CNu36Ue6wpBX.jpg",
      "trailer": "https://www.youtube.com/embed/D3RJhf865SQ",
      "formato": "Prime",
    },
    {
      "id": 1071585,
      "titulo": "M3GAN 2.0",
      "fecha": "2025-06-25",
      "duracion": 120,
      "clasificacion": "APT",
      "genero": "Acción, Ciencia ficción, Suspense",
      "sinopsis": "Con el futuro de la existencia humana en juego, Gemma se da cuenta de que la única opción es resucitar a M3GAN y darle unas cuantas mejoras, haciéndola más rápida, más fuerte y más letal.",
      "idioma": "EN",
      "poster": "https://image.tmdb.org/t/p/w500/zgsdwQ6XciR0IzgeRXyKzVhzVzP.jpg",
      "background": "https://image.tmdb.org/t/p/w500/cT9ZfwoPDk8JbgkessmQgxAWiaM.jpg",
      "trailer": "https://www.youtube.com/embed/P9Ku1BE3sDQ",
      "formato": "Regular",
    },
    {
      "id": 1197306,
      "titulo": "A Working Man",
      "fecha": "2025-03-26",
      "duracion": 116,
      "clasificacion": "APT",
      "genero": "Acción, Crimen, Suspense",
      "sinopsis": "Levon Cade dejó atrás una condecorada carrera militar en las operaciones encubiertas para vivir una vida sencilla trabajando en la construcción. Pero cuando la hija de su jefe, que para él es como de la familia, es secuestrada por traficantes de personas, su búsqueda para traerla a casa descubre un mundo de corrupción mucho mayor de lo que jamás podría haber imaginado.",
      "idioma": "EN",
      "poster": "https://image.tmdb.org/t/p/w500/aG50Ad3UV8cCQWpNWSHHUqgKGNB.jpg",
      "background": "https://image.tmdb.org/t/p/w500/fTrQsdMS2MUw00RnzH0r3JWHhts.jpg",
      "trailer": "https://www.youtube.com/embed/gGOXUdcE6hk",
      "formato": "Regular",
    },
    {
      "id": 950396,
      "titulo": "El abismo secreto",
      "fecha": "2025-02-13",
      "duracion": 127,
      "clasificacion": "APT",
      "genero": "Romance, Ciencia ficción, Suspense",
      "sinopsis": "Mandan a dos operativos de élite a vigilar lados opuestos de un misterioso abismo y allí intiman desde la distancia, pero deberán aunar fuerzas para sobrevivir al mal que esconde el abismo.",
      "idioma": "EN",
      "poster": "https://image.tmdb.org/t/p/w500/3s0jkMh0YUhIeIeioH3kt2X4st4.jpg",
      "background": "https://image.tmdb.org/t/p/w500/9nhjGaFLKtddDPtPaX5EmKqsWdH.jpg",
      "trailer": "https://www.youtube.com/embed/VuzKAeHGuMI",
      "formato": "Regular",
    },
    {
      "id": 1327862,
      "titulo": "A pesar de ti",
      "fecha": "2025-10-22",
      "duracion": 116,
      "clasificacion": "APT",
      "genero": "Romance, Drama",
      "sinopsis": "Morgan es una madre joven que intenta evitar que su hija Clara, de 16 años, cometa los mismos errores que ella, que se quedó embarazada y se casó demasiado joven, teniendo que aparcar sus propios sueños. La única persona que trae paz a la tensa relación madre-hija es Chris, su marido y padre de Clara. Pero esa paz se rompe cuando un trágico y extraño accidente trae desgarradoras consecuencias para ellas. Mientras lucha por reconstruir sus vidas, Morgan encuentra consuelo en la última persona que esperaba, mientras Clara se vuelve hacia el único chico que le han prohibido ver.",
      "idioma": "EN",
      "poster": "https://image.tmdb.org/t/p/w500/4lBPiTShr6vHvtnO7UBr35BarWs.jpg",
      "background": "https://image.tmdb.org/t/p/w500/amcOpAGkcTEZqmUG1LNM2gYGCam.jpg",
      "trailer": "https://www.youtube.com/embed/-Wsx4zQNHw4",
      "formato": "Regular",
    },
    {
      "id": 986056,
      "titulo": "Thunderbolts*",
      "fecha": "2025-04-30",
      "duracion": 127,
      "clasificacion": "APT",
      "genero": "Acción, Ciencia ficción, Aventura",
      "sinopsis": "Un grupo de supervillanos poco convencional es reclutado para hacer misiones para el gobierno: Yelena Belova, Bucky Barnes, Red Guardian, Ghost, Taskmaster y John Walker. Después de verse atrapados en una trampa mortal urdida por Valentina Allegra de Fontaine, estos marginados deben embarcarse en una peligrosa misión que les obligará a enfrentarse a los recovecos más oscuros de su pasado.",
      "idioma": "EN",
      "poster": "https://image.tmdb.org/t/p/w500/yDWU8YyFkPnlVY627QXPvct8bz9.jpg",
      "background": "https://image.tmdb.org/t/p/w500/rthMuZfFv4fqEU4JVbgSW9wQ8rs.jpg",
      "trailer": "https://www.youtube.com/embed/QCbzHZ1Q2lw",
      "formato": "Regular",
    },
    {
      "id": 950387,
      "titulo": "Una película de Minecraft",
      "fecha": "2025-03-31",
      "duracion": 100,
      "clasificacion": "APT",
      "genero": "Familia, Fantasía, Comedia, Aventura, Acción",
      "sinopsis": "Cuatro inadaptados se encuentran luchando con problemas ordinarios cuando de repente se ven arrastrados a través de un misterioso portal al Mundo Exterior: un extraño país de las maravillas cúbico que se nutre de la imaginación. Para volver a casa, tendrán que dominar este mundo mientras se embarcan en una búsqueda mágica con un inesperado experto artesano, Steve.",
      "idioma": "EN",
      "poster": "https://image.tmdb.org/t/p/w500/rZYYmjgyF5UP1AVsvhzzDOFLCwG.jpg",
      "background": "https://image.tmdb.org/t/p/w500/2Nti3gYAX513wvhp8IiLL6ZDyOm.jpg",
      "trailer": "https://www.youtube.com/embed/NOAmJa-dhCA",
      "formato": "Regular",
    },
    {
      "id": 1011477,
      "titulo": "Karate Kid: Legends",
      "fecha": "2025-05-08",
      "duracion": 94,
      "clasificacion": "APT",
      "genero": "Acción, Aventura, Drama",
      "sinopsis": "Tras una tragedia familiar, el prodigio del kung fu Li Fong se ve obligado a abandonar su hogar en Pekín y trasladarse a Nueva York con su madre. Li lucha por dejar atrás su pasado mientras intenta encajar con sus nuevos compañeros de clase y, aunque no quiere pelear, los problemas parecen encontrarle en todas partes. Nueva película de la saga \"Karate Kid\", conectada al universo de \"Cobra Kai\".",
      "idioma": "EN",
      "poster": "https://image.tmdb.org/t/p/w500/bwNAjGUsHt35eqT0Aj8NHU02WPl.jpg",
      "background": "https://image.tmdb.org/t/p/w500/7Q2CmqIVJuDAESPPp76rWIiA0AD.jpg",
      "trailer": "https://www.youtube.com/embed/rL0Ec_v4zVw",
      "formato": "Regular",
    },
    {
      "id": 1083433,
      "titulo": "Sé lo que hicisteis el último verano",
      "fecha": "2025-07-16",
      "duracion": 111,
      "clasificacion": "APT",
      "genero": "Terror, Misterio, Suspense",
      "sinopsis": "Cuando cinco amigos provocan sin querer un accidente de coche mortal, encubren su implicación y hacen un pacto para mantenerlo en secreto en lugar de afrontar las consecuencias. Un año después, su pasado vuelve para atormentarlos y se ven obligados a enfrentarse a una aterradora verdad: alguien sabe lo que hicieron el último verano... y está empeñado en vengarse. A medida que los amigos son acechados uno a uno por un asesino, descubren que esto ya ha sucedido antes, y recurren a dos supervivientes de la legendaria Masacre de Southport de 1997 en busca de ayuda.",
      "idioma": "EN",
      "poster": "https://image.tmdb.org/t/p/w500/iSbqO4oaXyUL17jB4YqPRpu7DeR.jpg",
      "background": "https://image.tmdb.org/t/p/w500/gVPjIcYo1gTaACF43OMsralrcUS.jpg",
      "trailer": "https://www.youtube.com/embed/l2v40fvWac0",
      "formato": "Prime",
    },
    {
      "id": 936108,
      "titulo": "Pitufos",
      "fecha": "2025-07-05",
      "duracion": 89,
      "clasificacion": "APT",
      "genero": "Animación, Familia, Fantasía",
      "sinopsis": "Película musical de animación centrada en las icónicas creaciones de Peyo. Cuando Papá Pitufo es secuestrado de forma misteriosa por los malvados brujos Razamel y Gargamel, Pitufina lleva a los Pitufos a una misión al mundo real para salvarle. Con la ayuda de nuevos amigos, los Pitufos deberán descubrir qué define su destino para salvar el universo.",
      "idioma": "EN",
      "poster": "https://image.tmdb.org/t/p/w500/zBdQclxQnEDOhDOjkKgKPW6jEHh.jpg",
      "background": "https://image.tmdb.org/t/p/w500/9whEVuKte4Qi0LI4TzPf7glinJW.jpg",
      "trailer": "https://www.youtube.com/embed/jYtjerVhaSA",
      "formato": "Regular",
    },
    {
      "id": 1151031,
      "titulo": "Devuélvemela",
      "fecha": "2025-05-28",
      "duracion": 104,
      "clasificacion": "APT",
      "genero": "Terror",
      "sinopsis": "Un hermano y su hermana descubren un aterrador ritual en la apartada casa de su nueva madre adoptiva. Lo que parece un hogar seguro pronto se convierte en una pesadilla, donde figuras siniestras, extrañas imágenes en vídeo y sucesos paranormales los rodean.",
      "idioma": "EN",
      "poster": "https://image.tmdb.org/t/p/w500/cl3VbcYxzWnDPetd7SbdhSxwWoL.jpg",
      "background": "https://image.tmdb.org/t/p/w500/2IIKts2A9vnUdM9tTC76B8tDmuZ.jpg",
      "trailer": "https://www.youtube.com/embed/wLMRLWSsfhw",
      "formato": "Regular",
    },
    {
      "id": 1125257,
      "titulo": "Ponte en mi lugar de nuevo",
      "fecha": "2025-08-06",
      "duracion": 111,
      "clasificacion": "APT",
      "genero": "Comedia, Fantasía, Familia",
      "sinopsis": "Años después de que Tess y Anna atravesaran una crisis de identidad, Anna ahora tiene una hija y una futura hijastra. Mientras enfrentan los innumerables desafíos que surgen cuando dos familias se fusionan, Tess y Anna descubren que el rayo puede caer dos veces.",
      "idioma": "EN",
      "poster": "https://image.tmdb.org/t/p/w500/3XFHVy03Rkr7ITaznFTeVp8dMwL.jpg",
      "background": "https://image.tmdb.org/t/p/w500/yQy9Y3p5INwkfTuHSnzYnz4MCV3.jpg",
      "trailer": "https://www.youtube.com/embed/thctDWzwjY0",
      "formato": "Regular",
    },
    {
      "id": 1100988,
      "titulo": "28 años después",
      "fecha": "2025-06-18",
      "duracion": 115,
      "clasificacion": "APT",
      "genero": "Terror, Suspense, Ciencia ficción",
      "sinopsis": "Años transcurridos tras los sucesos de \"28 semanas después\", el virus de la ira ha regresado y un grupo de supervivientes debe sobrevivir en un mundo asolado por hordas de infectados. Realizada con un iPhone 15 Pro Max y con la ayuda de numerosos accesorios especializados.",
      "idioma": "EN",
      "poster": "https://image.tmdb.org/t/p/w500/rlqdMZRPK8IELWcI5cJXLoA18XW.jpg",
      "background": "https://image.tmdb.org/t/p/w500/zav0v7gLWMu6pVwgsIAwt11GJ4C.jpg",
      "trailer": "https://www.youtube.com/embed/d-4F7jJUoOE",
      "formato": "Regular",
    },
    {
      "id": 1233413,
      "titulo": "Los pecadores",
      "fecha": "2025-04-16",
      "duracion": 138,
      "clasificacion": "APT",
      "genero": "Terror, Acción, Suspense",
      "sinopsis": "Tratando de dejar atrás sus problemáticas vidas, dos hermanos gemelos regresan a su pueblo natal para empezar de nuevo, solo para descubrir que un mal aún mayor les espera para darles la bienvenida.",
      "idioma": "EN",
      "poster": "https://image.tmdb.org/t/p/w500/zdClwqpYQXBSCGGDMdtvsuggwec.jpg",
      "background": "https://image.tmdb.org/t/p/w500/nAxGnGHOsfzufThz20zgmRwKur3.jpg",
      "trailer": "https://www.youtube.com/embed/XufPTI4PDLg",
      "formato": "Prime",
    },
    {
      "id": 1245993,
      "titulo": "Bala perdida",
      "fecha": "2025-08-26",
      "duracion": 107,
      "clasificacion": "APT",
      "genero": "Crimen, Suspense, Comedia",
      "sinopsis": "Cuando su vecino punki Russ le pide que cuide de su gato durante unos días, Hank Thompson se encuentra atrapado en medio de un variopinto grupo de gángsters amenazantes. Todos quieren algo de él; el problema es que él no sabe por qué. Mientras Hank intenta eludir sus cada vez más estrechas garras, tendrá que emplear toda su habilidad para mantenerse con vida el tiempo suficiente para averiguarlo…",
      "idioma": "EN",
      "poster": "https://image.tmdb.org/t/p/w500/dpEGQKgOeDo9GmmKDnEWjTLTi4u.jpg",
      "background": "https://image.tmdb.org/t/p/w500/41043LV7mfluH8iXEUPVseCDAv5.jpg",
      "trailer": "https://www.youtube.com/embed/RiYlMuK_RQA",
      "formato": "Regular",
    }

  ]


  