const dataDulceria = 
[
  {
    "id": 1,
    "titulo": "COMBO AURA",
    "descripcion": "1 Canchita grande salada + 1 Bebida (32oz)",
    "categoria": "combos",
    "precio": 24.00,
    "imagen": "../imagenes/10.png",
  },
  {
    "id": 2,
    "titulo": "COMBO AURA DULCE",
    "descripcion": "1 Canchita grande dulce + 1 Bebida (32oz)",
    "categoria": "combos",
    "precio": 27.00,
    "imagen": "../imagenes/11.png",
  },
  {
    "id": 3,
    "titulo": "COMBO MIX ESTELAR",
    "descripcion": "1 Canchita grande mixta + 1 Bebida (32oz)",
    "categoria": "combos",
    "precio": 27.00,
    "imagen": "../imagenes/12.png",
  },
  {
    "id": 4,
    "titulo": "COMBO DÚO AURA",
    "descripcion": "1 Canchita gigante salada + 2 Bebidas (32oz)",
    "categoria": "combos",
    "precio": 42.00,
    "imagen": "../imagenes/13.png",
    "background": "../imagenes/bg_combo_duo.jpg",
  },
  {
    "id": 5,
    "titulo": "COMBO DULCE GALÁCTICO",
    "descripcion": "1 Canchita gigante dulce + 2 Bebidas (32oz)",
    "categoria": "combos",
    "precio": 46.00,
    "imagen": "../imagenes/14.png",
    "background": "../imagenes/bg_combo_dulce_galactico.jpg",
  },
  {
    "id": 6,
    "titulo": "COMBO SUPER FAMILIAR",
    "descripcion": "1 Canchita extra gigante mixta + 4 Bebidas (32oz)",
    "categoria": "combos",
    "precio": 60.00,
    "imagen": "../imagenes/15.png",
    "background": "../imagenes/bg_combo_familiar.jpg",
  },
  {
    "id": 7,
    "titulo": "COMBO AVENTURA NACHERA",
    "descripcion": "Nachos con queso + 1 Bebida (32oz) + 1 Golosina",
    "categoria": "combos",
    "precio": 28.00,
    "imagen": "../imagenes/16.png",
    "background": "../imagenes/bg_combo_nachos.jpg",
  },
  {
    "id": 8,
    "titulo": "CANCHITA MEDIANA SALADA",
    "descripcion": "Ideal para una peli sin distracciones.",
    "categoria": "canchita",
    "precio": 11.00,
    "imagen": "../imagenes/8.png",
    "background": "../imagenes/bg_canchita.jpg",
  },
  {
    "id": 9,
    "titulo": "CANCHITA MEDIANA DULCE",
    "descripcion": "Caramelo suave, dorado y adictivo.",
    "categoria": "canchita",
    "precio": 13.00,
    "imagen": "../imagenes/9.png",
    "background": "../imagenes/bg_canchita_dulce.jpg",
  },
  {
    "id": 10,
    "titulo": "CANCHITA GRANDE EXTRA MANTEQUILLA",
    "descripcion": "Extra crujiente y sabrosa.",
    "categoria": "canchita",
    "precio": 15.00,
    "imagen": "../imagenes/7.png",
    "background": "../imagenes/bg_canchita_extra.jpg",
  },
  {
    "id": 11,
    "titulo": "CANCHITA GRANDE ACARAMELADO",
    "descripcion": "La combi perfecta entre dulce y salado.",
    "categoria": "canchita",
    "precio": 18.00,
    "imagen": "../imagenes/6.png",
    "background": "../imagenes/bg_canchita_mix.jpg",
  },
  {
    "id": 12,
    "titulo": "CANCHITA GIGANTE SALADA",
    "descripcion": "Para compartir (o no).",
    "categoria": "canchita",
    "precio": 20.00,
    "imagen": "../imagenes/3.png",
    "background": "../imagenes/bg_canchita_gigante.jpg",
  },
  {
    "id": 13,
    "titulo": "CANCHITA GIGANTE MIX",
    "descripcion": "La combi perfecta pero en versión gigante.",
    "categoria": "canchita",
    "precio": 24.00,
    "imagen": "../imagenes/1.png",
    "background": "../imagenes/bg_canchita_mixgigante.jpg",
  },
  {
    "id": 14,
    "titulo": "GASEOSA MEDIANA",
    "descripcion": "Sabor a elección (21 oz).",
    "categoria": "bebidas",
    "precio": 6.50,
    "imagen": "../imagenes/4.png",
    "background": "../imagenes/bg_bebidas.jpg",
  },
  {
    "id": 15,
    "titulo": "GASEOSA GRANDE",
    "descripcion": "Sabor a elección (32 oz).",
    "categoria": "bebidas",
    "precio": 8.50,
    "imagen": "../imagenes/5.png",
    "background": "../imagenes/bg_bebidas.jpg",
  },
  {
    "id": 16,
    "titulo": "FROZEN CINEAURA",
    "descripcion": "Granizado de sabores intensos (colores neón incluidos).",
    "categoria": "bebidas",
    "precio": 12.00,
    "imagen": "../imagenes/17.png",
    "background": "../imagenes/bg_frozen.jpg",
  },
  {
    "id": 17,
    "titulo": "AGUA MINERAL",
    "descripcion": "Para quienes buscan nivelar el azúcar (600 ml).",
    "categoria": "bebidas",
    "precio": 6.00,
    "imagen": "../imagenes/19.png",
    "background": "../imagenes/bg_agua.jpg",
  },
  {
    "id": 18,
    "titulo": "CAFÉ CALIENTE",
    "descripcion": "Para los amantes del café y el invierno.",
    "categoria": "bebidas",
    "precio": 7.00,
    "imagen": "../imagenes/18.png",
    "background": "../imagenes/bg_cafe.jpg",
  },
  {
    "id": 19,
    "titulo": "TABLETA DE CHOCOLATE",
    "descripcion": "70% cacao con un 10% de amor cinéfilo.",
    "categoria": "snacks",
    "precio": 7.50,
    "imagen": "../imagenes/20.png",
    "background": "../imagenes/bg_snacks.jpg",
  },
  {
    "id": 20,
    "titulo": "GOMITAS",
    "descripcion": "Colores, formas y sabores que explotan.",
    "categoria": "snacks",
    "precio": 6.00,
    "imagen": "../imagenes/21.png",
    "background": "../imagenes/bg_snacks.jpg",
  },
  {
    "id": 21,
    "titulo": "MINI COOKIES CHOCOCHIPS",
    "descripcion": "Crujientes y dulces, con chispas galácticas.",
    "categoria": "snacks",
    "precio": 7.00,
    "imagen": "../imagenes/22.png",
    "background": "../imagenes/bg_snacks.jpg",
  },
  {
    "id": 22,
    "titulo": "PALETA FANTASÍA",
    "descripcion": "Para grandes y chicos que aman el dulce y la fantasía.",
    "categoria": "snacks",
    "precio": 5.00,
    "imagen": "../imagenes/23.png",
    "background": "../imagenes/bg_snacks.jpg",
  },
  {
    "id": 23,
    "titulo": "SNACKS SALADOS",
    "descripcion": "Pretzels, papitas o nachitos para acompañar tu peli.",
    "categoria": "snacks",
    "precio": 5.00,
    "imagen": "../imagenes/24.png",
    "background": "../imagenes/bg_snacks.jpg",
  },
  {
    "id": 24,
    "titulo": "COMBO SOCIO CINEFAN",
    "descripcion": "1 Canchita grande + 1 gaseosa (32oz) + 1 golosina.",
    "categoria": "socio",
    "precio": 26.00,
    "imagen": "../imagenes/25.png",
    "background": "../imagenes/bg_socio.jpg",
  },
  {
    "id": 25,
    "titulo": "REFILL DE CANCHITA",
    "descripcion": "Recargas libres durante la película.",
    "categoria": "socio",
    "precio": 8.00,
    "imagen": "../imagenes/26.png",
    "background": "../imagenes/bg_socio.jpg",
  },
  {
    "id": 26,
    "titulo": "REFILL DE BEBIDA",
    "descripcion": "Recargas libres durante la película + Vaso Socio CineAura.",
    "categoria": "socio",
    "precio": 10.00,
    "imagen": "../imagenes/27.png",
    "background": "../imagenes/bg_socio.jpg",
  },
  {
    "id": 27,
    "titulo": "CANCHITA SOCIO 2x1",
    "descripcion": "Llévate 2 canchitas personales por el precio de 1.",
    "categoria": "socio",
    "precio": 11.00,
    "imagen": "../imagenes/28.png",
    "background": "../imagenes/bg_socio.jpg",
  },
];
